name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: install dependencies
      run: sudo apt-get install valgrind
    - name: test all
      run: valgrind ./main.exe
    - name: make clean
      run: make clean
